// Code generated by gs-mock v0.0.6. DO NOT EDIT.
// Source: https://github.com/go-spring/gs-mock
// gs mock -o src_mock.go -i '!RepositoryV2,,GenericService,Service,,Repository'

package example

import (
	"context"
	exp "github.com/go-spring/gs-mock/example/inner"
	"github.com/go-spring/gs-mock/gsmock"
	"io"
	"net/http"
)

// RepositoryMockImpl is a generated mock implementation of the Repository interface
// with type parameters [T ~int | ~uint, M *http.Request].
type RepositoryMockImpl[T ~int | ~uint, M *http.Request] struct {
	r *gsmock.Manager
}

// NewRepositoryMockImpl creates a new mock instance for Repository with the given
// gsmock.Manager and initializes the embedded interfaces.
func NewRepositoryMockImpl[T ~int | ~uint, M *http.Request](r *gsmock.Manager) *RepositoryMockImpl[T, M] {
	return &RepositoryMockImpl[T, M]{r: r}
}

//go:noinline
func (impl *RepositoryMockImpl[T, M]) funcFindByID() func(impl *RepositoryMockImpl[T, M], id string) (T, error) {
	return (*RepositoryMockImpl[T, M]).FindByID
}

// FindByID executes the mocked FindByID method.
func (impl *RepositoryMockImpl[T, M]) FindByID(id string) (T, error) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcFindByID(), impl, id); ok {
		return gsmock.Unbox2[T, error](ret)
	}
	panic("no mock code matched for RepositoryMockImpl.FindByID")
}

// MockFindByID returns a Mocker22 instance to register mock behavior for FindByID.
func (impl *RepositoryMockImpl[T, M]) MockFindByID() *gsmock.Mocker22[*RepositoryMockImpl[T, M], string, T, error] {
	return gsmock.Mock22(impl.funcFindByID(), impl.r)
}

//go:noinline
func (impl *RepositoryMockImpl[T, M]) funcSave() func(impl *RepositoryMockImpl[T, M], item T) error {
	return (*RepositoryMockImpl[T, M]).Save
}

// Save executes the mocked Save method.
func (impl *RepositoryMockImpl[T, M]) Save(item T) error {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcSave(), impl, item); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for RepositoryMockImpl.Save")
}

// MockSave returns a Mocker21 instance to register mock behavior for Save.
func (impl *RepositoryMockImpl[T, M]) MockSave() *gsmock.Mocker21[*RepositoryMockImpl[T, M], T, error] {
	return gsmock.Mock21(impl.funcSave(), impl.r)
}

// GenericServiceMockImpl is a generated mock implementation of the GenericService interface
// with type parameters [T any, R any].
type GenericServiceMockImpl[T any, R any] struct {
	io.Writer

	r *gsmock.Manager
}

// NewGenericServiceMockImpl creates a new mock instance for GenericService with the given
// gsmock.Manager and initializes the embedded interfaces.
func NewGenericServiceMockImpl[T any, R any](r *gsmock.Manager) *GenericServiceMockImpl[T, R] {
	return &GenericServiceMockImpl[T, R]{r: r}
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM00() func(impl *GenericServiceMockImpl[T, R]) {
	return (*GenericServiceMockImpl[T, R]).M00
}

// M00 executes the mocked M00 method.
func (impl *GenericServiceMockImpl[T, R]) M00() {
	if _, ok := gsmock.Invoke(impl.r, impl.funcM00(), impl); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.M00")
}

// MockM00 returns a Mocker10 instance to register mock behavior for M00.
func (impl *GenericServiceMockImpl[T, R]) MockM00() *gsmock.Mocker10[*GenericServiceMockImpl[T, R]] {
	return gsmock.Mock10(impl.funcM00(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM01() func(impl *GenericServiceMockImpl[T, R]) R {
	return (*GenericServiceMockImpl[T, R]).M01
}

// M01 executes the mocked M01 method.
func (impl *GenericServiceMockImpl[T, R]) M01() R {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM01(), impl); ok {
		return gsmock.Unbox1[R](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.M01")
}

// MockM01 returns a Mocker11 instance to register mock behavior for M01.
func (impl *GenericServiceMockImpl[T, R]) MockM01() *gsmock.Mocker11[*GenericServiceMockImpl[T, R], R] {
	return gsmock.Mock11(impl.funcM01(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM10() func(impl *GenericServiceMockImpl[T, R], r0 T) {
	return (*GenericServiceMockImpl[T, R]).M10
}

// M10 executes the mocked M10 method.
func (impl *GenericServiceMockImpl[T, R]) M10(r0 T) {
	if _, ok := gsmock.Invoke(impl.r, impl.funcM10(), impl, r0); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.M10")
}

// MockM10 returns a Mocker20 instance to register mock behavior for M10.
func (impl *GenericServiceMockImpl[T, R]) MockM10() *gsmock.Mocker20[*GenericServiceMockImpl[T, R], T] {
	return gsmock.Mock20(impl.funcM10(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM11() func(impl *GenericServiceMockImpl[T, R], r0 T) R {
	return (*GenericServiceMockImpl[T, R]).M11
}

// M11 executes the mocked M11 method.
func (impl *GenericServiceMockImpl[T, R]) M11(r0 T) R {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM11(), impl, r0); ok {
		return gsmock.Unbox1[R](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.M11")
}

// MockM11 returns a Mocker21 instance to register mock behavior for M11.
func (impl *GenericServiceMockImpl[T, R]) MockM11() *gsmock.Mocker21[*GenericServiceMockImpl[T, R], T, R] {
	return gsmock.Mock21(impl.funcM11(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM02() func(impl *GenericServiceMockImpl[T, R]) (R, bool) {
	return (*GenericServiceMockImpl[T, R]).M02
}

// M02 executes the mocked M02 method.
func (impl *GenericServiceMockImpl[T, R]) M02() (R, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM02(), impl); ok {
		return gsmock.Unbox2[R, bool](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.M02")
}

// MockM02 returns a Mocker12 instance to register mock behavior for M02.
func (impl *GenericServiceMockImpl[T, R]) MockM02() *gsmock.Mocker12[*GenericServiceMockImpl[T, R], R, bool] {
	return gsmock.Mock12(impl.funcM02(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM12() func(impl *GenericServiceMockImpl[T, R], r0 T) (R, bool) {
	return (*GenericServiceMockImpl[T, R]).M12
}

// M12 executes the mocked M12 method.
func (impl *GenericServiceMockImpl[T, R]) M12(r0 T) (R, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM12(), impl, r0); ok {
		return gsmock.Unbox2[R, bool](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.M12")
}

// MockM12 returns a Mocker22 instance to register mock behavior for M12.
func (impl *GenericServiceMockImpl[T, R]) MockM12() *gsmock.Mocker22[*GenericServiceMockImpl[T, R], T, R, bool] {
	return gsmock.Mock22(impl.funcM12(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcM22() func(impl *GenericServiceMockImpl[T, R], ctx context.Context, req map[string]T) (*Response, bool) {
	return (*GenericServiceMockImpl[T, R]).M22
}

// M22 executes the mocked M22 method.
func (impl *GenericServiceMockImpl[T, R]) M22(ctx context.Context, req map[string]T) (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM22(), impl, ctx, req); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for GenericServiceMockImpl.M22")
}

// MockM22 returns a Mocker32 instance to register mock behavior for M22.
func (impl *GenericServiceMockImpl[T, R]) MockM22() *gsmock.Mocker32[*GenericServiceMockImpl[T, R], context.Context, map[string]T, *Response, bool] {
	return gsmock.Mock32(impl.funcM22(), impl.r)
}

//go:noinline
func (impl *GenericServiceMockImpl[T, R]) funcPrintf() func(impl *GenericServiceMockImpl[T, R], format string, args ...any) {
	return (*GenericServiceMockImpl[T, R]).Printf
}

// Printf executes the mocked Printf method.
func (impl *GenericServiceMockImpl[T, R]) Printf(format string, args ...any) {
	if _, ok := gsmock.Invoke(impl.r, impl.funcPrintf(), impl, format, args); ok {
		return
	}
	panic("no mock code matched for GenericServiceMockImpl.Printf")
}

// MockPrintf returns a VarMocker30 instance to register mock behavior for Printf.
func (impl *GenericServiceMockImpl[T, R]) MockPrintf() *gsmock.VarMocker30[*GenericServiceMockImpl[T, R], string, any] {
	return gsmock.VarMock30(impl.funcPrintf(), impl.r)
}

// ServiceMockImpl is a generated mock implementation of the Service interface.
// It embeds the original interfaces and provides methods to register mock behaviors.
type ServiceMockImpl struct {
	io.Writer

	r *gsmock.Manager
}

// NewServiceMockImpl creates a new mock instance for Service with the given
// gsmock.Manager and initializes the embedded interfaces.
func NewServiceMockImpl(r *gsmock.Manager) *ServiceMockImpl {
	return &ServiceMockImpl{r: r}
}

//go:noinline
func (impl *ServiceMockImpl) funcM00() func(impl *ServiceMockImpl) {
	return (*ServiceMockImpl).M00
}

// M00 executes the mocked M00 method.
func (impl *ServiceMockImpl) M00() {
	if _, ok := gsmock.Invoke(impl.r, impl.funcM00(), impl); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.M00")
}

// MockM00 returns a Mocker10 instance to register mock behavior for M00.
func (impl *ServiceMockImpl) MockM00() *gsmock.Mocker10[*ServiceMockImpl] {
	return gsmock.Mock10(impl.funcM00(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM01() func(impl *ServiceMockImpl) *Response {
	return (*ServiceMockImpl).M01
}

// M01 executes the mocked M01 method.
func (impl *ServiceMockImpl) M01() *Response {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM01(), impl); ok {
		return gsmock.Unbox1[*Response](ret)
	}
	panic("no mock code matched for ServiceMockImpl.M01")
}

// MockM01 returns a Mocker11 instance to register mock behavior for M01.
func (impl *ServiceMockImpl) MockM01() *gsmock.Mocker11[*ServiceMockImpl, *Response] {
	return gsmock.Mock11(impl.funcM01(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM10() func(impl *ServiceMockImpl, r0 *exp.Request) {
	return (*ServiceMockImpl).M10
}

// M10 executes the mocked M10 method.
func (impl *ServiceMockImpl) M10(r0 *exp.Request) {
	if _, ok := gsmock.Invoke(impl.r, impl.funcM10(), impl, r0); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.M10")
}

// MockM10 returns a Mocker20 instance to register mock behavior for M10.
func (impl *ServiceMockImpl) MockM10() *gsmock.Mocker20[*ServiceMockImpl, *exp.Request] {
	return gsmock.Mock20(impl.funcM10(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM11() func(impl *ServiceMockImpl, r0 *exp.Request) *Response {
	return (*ServiceMockImpl).M11
}

// M11 executes the mocked M11 method.
func (impl *ServiceMockImpl) M11(r0 *exp.Request) *Response {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM11(), impl, r0); ok {
		return gsmock.Unbox1[*Response](ret)
	}
	panic("no mock code matched for ServiceMockImpl.M11")
}

// MockM11 returns a Mocker21 instance to register mock behavior for M11.
func (impl *ServiceMockImpl) MockM11() *gsmock.Mocker21[*ServiceMockImpl, *exp.Request, *Response] {
	return gsmock.Mock21(impl.funcM11(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM02() func(impl *ServiceMockImpl) (*Response, bool) {
	return (*ServiceMockImpl).M02
}

// M02 executes the mocked M02 method.
func (impl *ServiceMockImpl) M02() (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM02(), impl); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for ServiceMockImpl.M02")
}

// MockM02 returns a Mocker12 instance to register mock behavior for M02.
func (impl *ServiceMockImpl) MockM02() *gsmock.Mocker12[*ServiceMockImpl, *Response, bool] {
	return gsmock.Mock12(impl.funcM02(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM12() func(impl *ServiceMockImpl, r0 *exp.Request) (*Response, bool) {
	return (*ServiceMockImpl).M12
}

// M12 executes the mocked M12 method.
func (impl *ServiceMockImpl) M12(r0 *exp.Request) (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM12(), impl, r0); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for ServiceMockImpl.M12")
}

// MockM12 returns a Mocker22 instance to register mock behavior for M12.
func (impl *ServiceMockImpl) MockM12() *gsmock.Mocker22[*ServiceMockImpl, *exp.Request, *Response, bool] {
	return gsmock.Mock22(impl.funcM12(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcM22() func(impl *ServiceMockImpl, ctx context.Context, req map[string]*exp.Request) (*Response, bool) {
	return (*ServiceMockImpl).M22
}

// M22 executes the mocked M22 method.
func (impl *ServiceMockImpl) M22(ctx context.Context, req map[string]*exp.Request) (*Response, bool) {
	if ret, ok := gsmock.Invoke(impl.r, impl.funcM22(), impl, ctx, req); ok {
		return gsmock.Unbox2[*Response, bool](ret)
	}
	panic("no mock code matched for ServiceMockImpl.M22")
}

// MockM22 returns a Mocker32 instance to register mock behavior for M22.
func (impl *ServiceMockImpl) MockM22() *gsmock.Mocker32[*ServiceMockImpl, context.Context, map[string]*exp.Request, *Response, bool] {
	return gsmock.Mock32(impl.funcM22(), impl.r)
}

//go:noinline
func (impl *ServiceMockImpl) funcPrintf() func(impl *ServiceMockImpl, format string, args ...any) {
	return (*ServiceMockImpl).Printf
}

// Printf executes the mocked Printf method.
func (impl *ServiceMockImpl) Printf(format string, args ...any) {
	if _, ok := gsmock.Invoke(impl.r, impl.funcPrintf(), impl, format, args); ok {
		return
	}
	panic("no mock code matched for ServiceMockImpl.Printf")
}

// MockPrintf returns a VarMocker30 instance to register mock behavior for Printf.
func (impl *ServiceMockImpl) MockPrintf() *gsmock.VarMocker30[*ServiceMockImpl, string, any] {
	return gsmock.VarMock30(impl.funcPrintf(), impl.r)
}
